[tool.black]
line-length = 115
ensure_newline_before_comments = true

[tool.isort]
profile = "black"

# 1. Specify the order of import sections:
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"

# 2. Tell isort which modules are first‑party:
known_first_party = ["core", "models", "schemas", "validators"]

# 3. (Optional) Auto‑comment headings for visual clarity:
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third‑Party Libraries"
import_heading_firstparty = "Local Application Imports"
